version: "3.5"

services:

  apigw:
    image: apigw:1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./hero.pfx:/app/hero.pfx
      - ./appsettingsapigw.yml:/app/appsettings.yml
    extra_hosts:
      - ${EXTRAHOSTS}
    networks:
      - web-net
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/hero.pfx
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8443
    deploy:
      labels:
        - "traefik.http.routers.${APPNAME}.tls=true"
        - "traefik.http.services.${APPNAME}.loadbalancer.server.port=8443"
        - "traefik.enable=true"
        - "traefik.http.routers.${APPNAME}.rule=Host(`${APPNAME}.${DOMAIN}`)"
        - "traefik.http.routers.${APPNAME}.entrypoints=web"
        - "traefik.http.routers.${APPNAME}.entrypoints=websecure"
        - "traefik.http.services.${APPNAME}.loadBalancer.sticky.cookie=true"
        - "traefik.http.services.${APPNAME}.loadBalancer.sticky.cookie.name=${APPNAME}_cookie"
        - "traefik.http.services.${APPNAME}.loadbalancer.server.scheme=https"
        - "traefik.http.routers.${APPNAME}.tls.certresolver=myresolver"
      mode: replicated
      replicas: 1

networks:
  web-net:
    external: true
