version: "3.5"

services:

  apigw:
    image: ${IMAGE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../${PFX}:/app/${PFX}
      - ../${APPSETTINGSYML}:/app/appsettings.yml
    extra_hosts:
      - ${EXTRAHOSTS}
    networks:
      - web-net
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${PFXPWD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/${PFX}
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8443
    deploy:
      labels:
        - "traefik.http.routers.${APPNAME}.tls=true"
        - "traefik.http.services.${APPNAME}.loadbalancer.server.port=8443"
        - "traefik.enable=true"
        - "traefik.http.routers.${APPNAME}.rule=Host(`heroapi.heroma.test`)"
        - "traefik.http.routers.${APPNAME}.entrypoints=web"
        - "traefik.http.routers.${APPNAME}.entrypoints=websecure"
        - "traefik.http.services.${APPNAME}.loadBalancer.sticky.cookie=true"
        - "traefik.http.services.${APPNAME}.loadBalancer.sticky.cookie.name=heroapigw_cookie"
        - "traefik.http.services.${APPNAME}.loadbalancer.server.scheme=https"
      mode: replicated
      replicas: 1

networks:
  web-net:
    external: true
